<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "femanagerextended"
 *
 * Auto generated by Extension Builder 2013-06-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'femanagerextended',
    'description' => 'Extend fe_users and femanager with a new field and a new validation',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'author_company' => '',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'experimental',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '4.0.0-dev',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
            'femanager' => '8.0.0-',
        ],
    ],
];
