<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "femanagerextended"
 *
 * Auto generated by Extension Builder 2013-06-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'femanagerextended',
	'description' => 'Extend fe_users and femanager with a new field and a new validation',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0.0-6.2.99',
			'fluid' => '6.0.0-6.2.99',
			'typo3' => '6.0.0-6.2.99',
			'femanager' => '1.0.0-1.99.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>