services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    In2code\Femanagerextended\:
      resource: '../Classes/*'
      exclude: '../Classes/Domain/Model/*'
